### ISSUE TITLE
OpenBVE crashes

### ISSUE THREAD

**Issue by LOL-Bot-KC** [Kenny-Hui/obDRPC#2]
When closing doors, it automatically crashes and open a new game window

OpenBVE Version: Nightly build 2022-09-06

**Comment by AmberIsFrozen** [comment]
Can you upload the crash log?
On the main OpenBVE Menu, you can click **Report Problem** on the bottom left, then click **View the Previous crash log**
![image](https://user-images.githubusercontent.com/28094366/198868133-6fd65a82-796e-4205-ad71-cfae7c9ddb5f.png)

**Comment by LOL-Bot-KC** [comment]
[OpenBVE Crash- 2022.10.30[17.55].log](https://github.com/Kenny-Hui/obDRPC/files/9895552/OpenBVE.Crash-.2022.10.30.17.55.log)

**Comment by AmberIsFrozen** [comment]
The URL you provided on the button is invalid
You can specify them with a pipe character like so:
![image](https://user-images.githubusercontent.com/28094366/198876886-42cdc4f3-8bf9-45b2-84a6-3220f363b294.png)

However I will be considering adding a warning instead of a crash, thanks for the report.

**Comment by LOL-Bot-KC** [comment]
I see, thank you for answering!
